#pragma config(Sensor, S1,     distance,       sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     color,          sensorEV3_Color)
#pragma config(Sensor, S3,     angle,          sensorEV3_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Variables
const int blackLine = 16;
const int white = 90;
const int lineFollowTarget = 75;
const bool right = true;
const bool left = false;

#include "Functions.h"
#include "Stages.h"


//Main program ----------------------------------------------------------------------------------------------------------------------------------------
task main()
{
	wait1Msec(5000);
	//Track section
	stage1();

	//Buttle stuff
	stage2();

}
