#pragma config(Sensor, S1,     distance,       sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     color,          sensorEV3_Color)
#pragma config(Sensor, S3,     angle,          sensorEV3_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Variables
int blackLine = 16;
int white = 90;
int lineFollowTarget = 75;
bool right = true;
bool left = false;

//Functions
void lineFollower(float multiplier,  bool side, int speed);
void stopMotors();
void lfToBlack(int threshold, bool side);
void turnDeg(int deg);
void JumpLine(int times);
void openArm();
void closeArm();

//Main program ----------------------------------------------------------------------------------------------------------------------------------------
task main()
{
	//Stop 1
	lfToBlack(blackLine, left);

	//Skift spor
	turnDeg(-30);
	JumpLine(1);
	lfToBlack(55, left);
	turnDeg(40);

	//Stop 2
	lfToBlack(blackLine, left);

	//Skift spor
	turnDeg(30);
	JumpLine(1);
	lfToBlack(55, left);
	turnDeg(-10);

	//Stop 3

	lfToBlack(blackLine, right);
	JumpLine(3);
	wait1Msec(200);

	setMotorTarget(motorB, 100, -40);
	wait1Msec(600);

	//JumpLine();
	//turnDeg(10);
	//Stop 4 (Bottle)
	//Drive to bottle

	while(getUSDistance(S1) > 7.5){
		lineFollower(0.7, false,20);
	}
	setMotorSync(motorA,motorB,0,0);
	//Close arm
	closeArm();

	JumpLine(4);

	//Open arm
	openArm();
	wait1Msec(3000);
	while(getUSDistance(S1) > 7.5){
		setMotorSync(motorA,motorB,0,20);
	}
	stopMotors();
	//Close arm
	closeArm();

	//Stop 5
	//turnDeg(-150);
	setMotorTarget(motorB, 1000, 40);
	wait1Msec(1000);
	JumpLine(5);

	//Drive to line
	setMotorSync(motorA, motorB, 0, 40);
	while(getColorReflected(S2) > white){
		wait1Msec(10);
	}
	stopMotors();

	lfToBlack(blackLine, right);

	//Stop 6 (Efter vippe)
	JumpLine(1);
	lfToBlack(blackLine, right);


}

//FUNCTIONS -------------------------------------------------------------------------------------------------------------------------------------------
//Line following, if side true go on right

void lfToBlack(int threshold, bool side){
	//Linefollow intil it reads black
	while(getColorReflected(S2) > threshold){
		//Values for following the yellow lines
		lineFollower(0.7, side,40);
	}
	stopMotors();
}

void lineFollower(float multiplier, bool side, int speed){
	string t1;
	int col1 = getColorReflected(S2);
	sprintf(t1,"farve: %d", col1);
	displayCenteredBigTextLine(1,t1);

	int error = (lineFollowTarget - col1) * (side ? -1: 1);
	float difSpeed = error * multiplier;

	setMotorSync(motorA, motorB, difSpeed, speed);
}


void turnDeg(int deg){
	resetGyro(S3);
	int meas = getGyroHeading(S3);
	int error = meas - deg;
	while( error != 0 ){
		//Turn the car(Speed it up later)
		setMotorSync(motorA, motorB, 100 * ( error < 0 ? 1 : -1 ), 20);
		meas = getGyroHeading(S3);

		string t1;
		sprintf(t1,"farve: %d", error);
		displayCenteredBigTextLine(1,t1);
		error = meas - deg;
	}
	stopMotors();
}

//Stop motors
void stopMotors(){
	setMotorSync(motorA, motorB, 0, 0);
}

//Drive over black line
void JumpLine(int times){
	setMotorSync(motorA, motorB, 0, 40);
	wait1Msec(200*times);
	stopMotors();
}

void closeArm(){
	setMotorTarget(motorC,2000,40);
	wait1Msec(2800);
}

void openArm(){
	setMotorTarget(motorC,-100,40);
	wait1Msec(1300);
}
