#pragma config(Sensor, S1,     touch,          sensorEV3_Touch)
#pragma config(Sensor, S2,     color,          sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//displayCenterBigTextLine(int lin, str txt);
//setMotorTarget(motor, int afst, int hast)
//setMotorSpeed
setMotorSync(motorA, motorB);
task main()
{

	while(true){
		//80
	/*	if(SensorValue[S2] > 40 && SensorValue[S2] < 50){
			motor[motorA] = 70;
			motor[motorB]=70;
	}*/
		if(SensorValue[S2] /*getColorReflected(S1)*/<= 45 /*&& SensorValue[S2] > 6 */){
			motor[motorA] = 0;
			motor[motorB]=30;
		}
		else if(SensorValue[S2] > 45){
			motor[motorA] = 30;
			motor[motorB]=0;
		}
		/*else if(SensorValue[S2] < 6){
			motor[motorA] = 0;
			motor[motorB]=0;
		}*/

	}
}
